apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tasks.fullname" . }}
  labels:
    {{- include "tasks.labels" . | nindent 4 }}
data:
  {{- (.Files.Glob "files/*").AsConfig | nindent 2 }}
