apiVersion: v1
kind: ServiceAccount
metadata:
  name: git-access
  labels:
    {{- include "tasks.labels" . | nindent 4 }}
secrets:
  - name: github-credentials
  - name: gitlab-credentials
---
apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
  name: github-credentials
  labels:
    {{- include "tasks.labels" . | nindent 4 }}
  annotations:
    tekton.dev/git-0: "https://github.com"
    replicator.v1.mittwald.de/replicate-from: qgc-secrets/github-credentials
data:
  username: ""
  password: ""
---
apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
  name: gitlab-credentials
  labels:
    {{- include "tasks.labels" . | nindent 4 }}
  annotations:
    tekton.dev/git-1: "https://gitlab.com"
    replicator.v1.mittwald.de/replicate-from: qgc-secrets/gitlab-credentials
data:
  username: ""
  password: ""
