apiVersion: v1
kind: ServiceAccount
metadata:
  name: git-access
  labels:
    {{- include "tasks.labels" . | nindent 4 }}
secrets:
  - name: github-credentials
  - name: gitlab-credentials
{{ range $i, $gitSecret := .Values.gitSecrets.definition }}
{{ $secretName := print $gitSecret.name "-credentials" }}
{{ $secret := (lookup "v1" "Secret" $.Values.gitSecrets.source $secretName) }}
---
apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "tasks.labels" $ | nindent 4 }}
  annotations:
    tekton.dev/git-{{ $i }}: "{{ $gitSecret.url }}"
data:
  {{ toYaml $secret.data | nindent 2 }}
{{ end }}
