apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tasks.fullname" . }}-maven
  labels:
    {{- include "tasks.labels" . | nindent 4 }}
data:
  settings.xml: |-
    {{- .Files.Get "files/maven/settings.xml" | nindent 4 }}