apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tasks.fullname" . }}-npm
  labels:
    {{- include "tasks.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.npmDefaultEnv | nindent 2 }}
