apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "tasks.serviceAccountName" . }}
  labels:
    {{- include "tasks.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: git-access
  - kind: ServiceAccount
    name: {{ include "tasks.serviceAccountName" . }}-container-analyzer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "tasks.serviceAccountName" . }}
