apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "tasks.serviceAccountName" . }}
  labels:
    {{- include "tasks.labels" . | nindent 4 }}
rules:
  # Permissions to create update task run
  - apiGroups: ["tekton.dev"]
    resources: ["taskruns"]
    verbs: ["list", "get", "patch"]
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get"]
